services:
  db:
    image: postgres:16
    container_name: tierlist-db
    environment:
      POSTGRES_USER: tieruser
      POSTGRES_PASSWORD: tierpass
      POSTGRES_DB: tierdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tierlist-backend
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=tierdb;Username=tieruser;Password=tierpass"
    volumes:
      - imagesdata:/app/images

  frontend:
    build:
      context: ./front
    container_name: tierlist-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  dbdata:
  imagesdata:  
